version: '3'

services:

  nginx1:
    image:  nginx:alpine
    volumes:
      - ./var-www:/usr/share/nginx/html

  nginx1:
    image: nginx:alpine
    volumes:
      - ./var-www:/usr/share/nginx/html
  proxy:
    image: haproxy:alpine
    links:
      - hastebin01
      - hastebin02
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

